### ISSUE TITLE
redis > 4.2.2 & fakeredis 1.7.4 & python3.8 - KeyError: 'connection_pool'

### ISSUE THREAD

**Issue by danstreeter** [dsoftwareinc/fakeredis-py#5]
**Describe the bug**  
A recent upgrade of our libraries upgraded the `redis` library from `3.5.3` to `4.2.2` - All tests that were using `fakeredis` now fail with a `KeyError: 'connection_pool'` error.

Upon producing the reproduction steps I noticed that there is a compatibility issue between `fakeredis 1.7.4` and the current latest version of redis which is `redis 4.3.1` so reverted to `redis 4.2.2` for the purposes of this replication to avoid this incompatibility where the issue still occurs.

I've tried to look back through `fakeredis.FakeStrictRedis -> FakeRedisMixin` which references this key in this bit of code: https://github.com/dsoftwareinc/fakeredis-py/blob/master/fakeredis/_server.py#L2804 which is where the test traceback also references.

**To Reproduce**  
_I am working in pipenv, so as follows:_
Install environment and required packages

```bash
pipenv --python 3.8.12 install "fakeredis[lua]~=1.7.4" "redis~=4.2.2" "pytest"
```

_I am using the lua extra to be closer to the application_

Create a sample test file with the following contents:

```python
import fakeredis
import pytest


def test_example():

    redis = fakeredis.FakeStrictRedis(decode_responses=True)

    expected = True
    output = True
    assert expected == output
```

Run the test:

```bash
pipenv run pytest test_example.py
```

Review the output:

```bash
========================== test session starts ==========================
platform darwin -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/danstreeter/temp/fakeredis-bug
collected 1 item

fakeredis_test.py F                                               [100%]

=============================== FAILURES ================================
_____________________________ test_example ______________________________

    def test_example():

>       redis = fakeredis.FakeStrictRedis(decode_responses=True)

fakeredis_test.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'FakeStrictRedis' object has no attribute 'connection_pool'") raised in repr()] FakeStrictRedis object at 0x10d442d90>
server = None, connected = True, args = ()
kwargs = {'decode_responses': True}
bound = <BoundArguments (args=(), kwds={'decode_responses': True})>

    def __init__(self, *args, server=None, connected=True, **kwargs):
        # Interpret the positional and keyword arguments according to the
        # version of redis in use.
        bound = _ORIG_SIG.bind(*args, **kwargs)
        bound.apply_defaults()
>       if not bound.arguments['connection_pool']:
E       KeyError: 'connection_pool'

.venv/lib/python3.8/site-packages/fakeredis/_server.py:2804: KeyError
======================== short test summary info ========================
FAILED fakeredis_test.py::test_example - KeyError: 'connection_pool'
=========================== 1 failed in 0.18s ===========================
```

**Expected behavior**  
I guess, for it to not fail - or some advice on how to provide a `connection_pool` parameter to the required `FakeRedis` instance.

**Desktop (please complete the following information):**

 - OS: OSX Monterey 12.3
 - python version - 3.8
 - redis-py version - 4.3.1
 - full requirements.txt?

```bash
pipenv lock -r

Warning: The lock flag -r/--requirements will be deprecated in a future version
of pipenv in favor of the new requirements command. For more info see
https://pipenv.pypa.io/en/latest/advanced/#generating-a-requirements-txt
NOTE: the requirements command parses Pipfile.lock directly without performing any
locking operations. Updating packages should be done by running pipenv lock.
#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv lock --requirements
#

-i https://pypi.org/simple
async-timeout==4.0.2; python_version >= '3.6'
attrs==21.4.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
deprecated==1.2.13; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
fakeredis[lua]==1.7.4
iniconfig==1.1.1
lupa==1.13
packaging==21.3; python_version >= '3.6'
pluggy==1.0.0; python_version >= '3.6'
py==1.11.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
pyparsing==3.0.9; python_full_version >= '3.6.8'
pytest==7.1.2
redis==4.2.2
six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
sortedcontainers==2.4.0
tomli==2.0.1; python_version >= '3.7'
wrapt==1.14.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
```

**Additional context**  
Happy to assist in debugging if I can. =)

**Comment by cunla** [comment]
The package currently does not work with python3.8 and redis >= 4.2.
See #3 as well.
I would be happy if you can assist with it.

**Comment by ericman93** [comment]
I still have this issue in `1.7.5`
```
self = <[AttributeError("'FakeStrictRedis' object has no attribute 'connection_pool'") raised in repr()] FakeStrictRedis object at 0x7f578bffb0d0>
server = None, connected = True, args = (), kwargs = {}
default_args = odict_values([<Parameter "*args">, <Parameter "**kw">])
kwds = {}
    def __init__(self, *args, server=None, connected=True, **kwargs):
        # Interpret the positional and keyword arguments according to the
        # version of redis in use.
        default_args = inspect.signature(redis.Redis.__init__).parameters.values()
        kwds = {p.name: p.default for p in default_args if p.default != inspect._empty}
        kwds.update(kwargs)
        # bound = _ORIG_SIG.bind(*args, **params)
        # kwds = bound.arguments['kwds']
>       if not kwds['connection_pool']:
E       KeyError: 'connection_pool'
```

it is working locally, but not in github action

**Comment by cunla** [comment]
> I still have this issue in `1.7.5`
> 
> ```
> self = <[AttributeError("'FakeStrictRedis' object has no attribute 'connection_pool'") raised in repr()] FakeStrictRedis object at 0x7f578bffb0d0>
> server = None, connected = True, args = (), kwargs = {}
> default_args = odict_values([<Parameter "*args">, <Parameter "**kw">])
> kwds = {}
>     def __init__(self, *args, server=None, connected=True, **kwargs):
>         # Interpret the positional and keyword arguments according to the
>         # version of redis in use.
>         default_args = inspect.signature(redis.Redis.__init__).parameters.values()
>         kwds = {p.name: p.default for p in default_args if p.default != inspect._empty}
>         kwds.update(kwargs)
>         # bound = _ORIG_SIG.bind(*args, **params)
>         # kwds = bound.arguments['kwds']
> >       if not kwds['connection_pool']:
> E       KeyError: 'connection_pool'
> ```
> 
> it is working locally, but not in github action

Hi @ericman93, can you create a new issue and explain how you are using it in your github action?
