### ISSUE TITLE
Fakeredis 1.7.4 not compatible with Python 3.10

### ISSUE THREAD

**Issue by jantony-athene** [dsoftwareinc/fakeredis-py#4]
**Describe the bug**
Unable to install fakeredis 1.74 with Python 3.10

**To Reproduce**
1. Install Python 3.10 with openssl-1.1.1o
2. Pip install fakeredis
3. Error received as below

```
  Running setup.py install for hiredis: started
  Running setup.py install for hiredis: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for hiredis did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /tmp/pip-install-_d6d1y9g/hiredis_a71de6dff6b144529f910eb349fefc27/setup.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import sys, imp, os, glob, io
      /usr/local/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/hiredis
      copying hiredis/__init__.py -> build/lib.linux-x86_64-3.10/hiredis
      copying hiredis/version.py -> build/lib.linux-x86_64-3.10/hiredis
      copying hiredis/hiredis.pyi -> build/lib.linux-x86_64-3.10/hiredis
      copying hiredis/py.typed -> build/lib.linux-x86_64-3.10/hiredis
      warning: build_py: byte-compiling is disabled, skipping.
      
      running build_ext
      building 'hiredis.hiredis' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/src
      creating build/temp.linux-x86_64-3.10/vendor
      creating build/temp.linux-x86_64-3.10/vendor/hiredis
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ivendor -I/usr/local/include/python3.10 -c src/hiredis.c -o build/temp.linux-x86_64-3.10/src/hiredis.o
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ivendor -I/usr/local/include/python3.10 -c src/reader.c -o build/temp.linux-x86_64-3.10/src/reader.o
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ivendor -I/usr/local/include/python3.10 -c vendor/hiredis/alloc.c -o build/temp.linux-x86_64-3.10/vendor/hiredis/alloc.o
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ivendor -I/usr/local/include/python3.10 -c vendor/hiredis/read.c -o build/temp.linux-x86_64-3.10/vendor/hiredis/read.o
      vendor/hiredis/read.c: In function 'redisReaderFree':
      vendor/hiredis/read.c:646:9: error: 'for' loop initial declarations are only allowed in C99 mode
               for (int i = 0; i < r->tasks; i++) {
               ^
      vendor/hiredis/read.c:646:9: note: use option -std=c99 or -std=gnu99 to compile your code
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hiredis

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Expected behavior**
Clean install

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - python version: 3.10.4
 - redis-py version: 4.2.2

**Comment by cunla** [comment]
It looks like you are installing `hiredis` and not `fakeredis`
What command are you using to install `fakeredis`?
Running `pip install fakeredis` works fine with _python3.10_

**Comment by jantony-athene** [comment]
@cunla that's true.
I had earlier mistook `hiredis` as a dependency for `fakeredis`.
We can close this.
Thank you!
